### ISSUE TITLE
Support for MultiPart Rars

### ISSUE THREAD

**Issue by thewillwilson** [Jorricks/unrar-angel#1]
How well does this script work with multi-part rars?

**Comment by Jorricks** [comment]
My multi-part rars always have a .rar file in there which is then connected to the .r00 .r01 etc. part. The program simply takes the .rar file and tries to extract it. The actual unrar library from winrar then automatically unpacks all the files that are linked to the .rar file. 

If you have any other questions or more in depth, let me know.
Closing this issue now :)

**Comment by Jorricks** [comment]
Closed
